# Generated by Django 4.0.4 on 2022-05-18 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0004_description_job_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='description',
            name='avator',
            field=models.FileField(blank=True, default='', null=True, upload_to='avator'),
        ),
    ]
