# Generated by Django 4.0.4 on 2022-05-18 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0005_description_avator'),
    ]

    operations = [
        migrations.AlterField(
            model_name='description',
            name='avator',
            field=models.FileField(blank=True, default='no.img.png', null=True, upload_to='avator'),
        ),
    ]
