# Generated by Django 4.0.4 on 2022-05-18 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0007_alter_description_avator'),
    ]

    operations = [
        migrations.AlterField(
            model_name='description',
            name='avator',
            field=models.FileField(default='media/no_img.png', upload_to='avator'),
        ),
    ]
